### PR TITLE
A suite of redis memory optimizations

### LINKED ISSUE #31: Optimization: Invariant payloads
As detailed in: https://github.com/QutBioacoustics/baw-private/issues/110#issuecomment-152883850

Enqueuing a large batch of jobs (330K) creates as many entries in Redis. Currently, the entire job payload is duplicated even though 90% of it does not change. In particular, verbose configuration files (like in the `Towsey.Acoustic.yml` case) take up 3715/4239 chars, *88%* of the payload. For 330K - 1 jobs, 3715 bytes are redundant; that is 1.23GB of unnecessary RAM use on a redis instance.

Investigate methods of storing the bulk of the payload (especially the config strings) only once. I'm thinking a redis ~~hash~~ string value where the key is ~~the SHA of the config, and the value is the config~~ `{{namespace}}:{{object-type}}:{{id}}` and the value is the JSON encoded rest of the payload. Jobs then do two redis operations, one for the payload (done by resque) and one for the ~~config~~ rest of they payload (the invariant payload). An example key may look like: `baw-workers:analysis_job:123` or `baw-workers:analysis_job:system:index_genration`.

Important requirements:
- must be able to work with a full payload or a partial payload
- must be able to work for system jobs or analysis jobs
- invariant payload creation can be invoked elsewhere
  - Analysis jobs can delete their payloads when created and finished.
  - System jobs should periodically update their invariant payload
- the invariant payload should have a reasonable TTL  - something like 3 months. 
- a normal payload will have a special key in it's JSON string. The key, named `payload-base`, will contain the absolute redis key to the rest of the payload. E.g.
```json
{
  "uuid": "7d78905e-5ea9-4a95-b568-0f14c2f37e4c",
  "id": 1234,
  "payload-base": "baw-workers:analysis_job:123"
}
```

### LINKED ISSUE #40: Resque:status not deleting keys.
Issue explained by https://github.com/quirkey/resque-status/issues/76

We currently only initialize `Resque::Plugins::Status::Hash.expire_in` in baw_server.

When the workers actually run the status keys never get a TTL. This causes every payload for every job we have to be stored indefinitely.

### LINKED ISSUE #41: Resque:status duplicates payload when storing its data
Caused by this line here: https://github.com/quirkey/resque-status/blob/11eb130ad1bc9cbc11aae3bad4d507ee06f5bb0a/lib/resque/plugins/status.rb#L249

When storing the status, resque:status stores the `status`, the `args` (the resque payload), and a `name`. Unless that name is overridden in the base class, it defaults to `.to_s`ing the status class, to which we have attached most  of the payload again as instance variables, which results in a *very* long string, containing duplicated (and escaped data), and effectively doubles payload size!

Solution: implement `name` method in action classes.

---

Example of **just** the name field from one of resque:status' strings:

```
"name": 
"BawWorkers::Analysis::Action({\"analysis_params\"=>{\"command_format\"= 
>\"mono \\\"<{file_executable}>\\\" audio2csv 
/source:\\\"<{file_source}>\\\" /config:\\\"<{file_config}>\\\" 
/tempdir:\\\"<{dir_temp}>\\\" /output:\\\"<{dir_output}>\\\"\", 
\"file_executable\"=>\"./AnalysisPrograms/AnalysisPrograms.exe\", 
\"copy_paths\"=>[\"./programs/AnalysisPrograms/Logs/log.txt\"], 
\"config\"=>\"---\\r\\n# Summary: Calculates acoustic 
indices\\r\\n#\\r\\n# The csv files this analysis outputs can be used to 
construct:\\r\\n# 1. long-duration false-color spectrograms\\r\\n# 2. a 
focused stack of zooming false-color spectrograms\\r\\n# 3. the tiles 
for zooming false-color 
spectrograms\\r\\n#\\r\\n#\\r\\n\\r\\nAnalysisName: 
Towsey.Acoustic\\r\\n#SegmentDuration: units=minutes; SegmentOverlap: 
units=seconds;\\r\\nSegmentDuration: 1\\r\\nSegmentOverlap: 
0\\r\\n\\r\\n# IndexCalculationDuration: units=seconds (default=60 
seconds; use 0.2 for zooming spectrogram tiles)\\r\\n# The Timespan (in 
seconds) over which summary and spectral indices are 
calculated\\r\\nIndexCalculationDuration: 60.0\\r\\n\\r\\n# 
BGNoiseNeighbourhood: units=seconds (default IndexCalculationDuration = 
60 seconds)\\r\\n# BG noise for any location is calculated by extending 
the region of index calculation from 5 seconds before start to 5 sec 
after end of current index interval.\\r\\n# Ten seconds is considered a 
minimum interval to obtain a reliable estimate of BG noise.\\r\\n# The 
BG noise interval is not extended beyond start or end of recording 
segment.\\r\\n# Consequently for a 60sec Index calculation duration, the 
BG noise is calculated form the 60sec segment 
only.\\r\\nBGNoiseNeighbourhood: 5\\r\\n\\r\\n# FRAME LENGTH. 
units=samples\\r\\n# FrameWidth is used without overlap to calculate the 
spectral indices. Typical value=512\\r\\nFrameLength: 512\\r\\n\\r\\n# 
Resample rate must be 2 X the desired Nyquist\\r\\n# ResampleRate: 
17640\\r\\nResampleRate: 22050\\r\\n\\r\\n#Default values in code are 
LowFreqBound=500Hz & MidFreqBound=4000\\r\\nLowFreqBound: 
500\\r\\nMidFreqBound: 4000\\r\\nHighFreqBound: 8010 
\\r\\n\\r\\nDisplayWeightedIndices: false\\r\\n\\r\\n# SAVE INTERMEDIARY 
FILES\\r\\nSaveIntermediateWavFiles: 
false\\r\\nSaveIntermediateCsvFiles: false\\r\\n\\r\\n# SAVE SONOGRAM 
DATA FILES FOR SUBSEQUENT ZOOMING SPECTROGRAMS\\r\\n# Next two 
parameters are used only when creating images for zooming 
spectrograms.\\r\\n# Warning: IndexCalculationDuration must be set = 0.2 
when SaveSonogramData = true\\r\\n# TODO: this option should be 
refactored out into the spectrogram generation analyzer - currently 
confusing implementation\\r\\nSaveSonogramData: false\\r\\n# Frame step. 
units=samples\\r\\n# NOTE: The value for FrameStep is used only when 
calculating a standard spectrogram within the ZOOMING spectrogram 
function.\\r\\n# FrameStep is NOT used when calculating Summary and 
Spectral indices.\\r\\n# However the FrameStep entry must NOT be deleted 
from this file. Keep the value for when it is required. \\r\\n# The 
value 441 should NOT be changed because it has been calculated 
specifically for current ZOOMING spectrogram set-up.\\r\\n# TODO: this 
option should be refactored out into the spectrogram generation analyzer 
- currently confusing implementation\\r\\nFrameStep: 441\\r\\n\\r\\n# 
One-minute spectrograms can be saved in any analysis 
task.\\r\\nSaveSonogramImages: false\\r\\n\\r\\nDisplayCsvImage: 
false\\r\\nDoNoiseReduction: true\\r\\nBgNoiseThreshold: 
3.0\\r\\nSonogramBackgroundThreshold: 4.0\\r\\nParallelProcessing: 
true\\r\\n\\r\\n# if true an additional set of images will be produced 
that are tiles\\r\\n# if true, RequireDateInFilename must be 
set\\r\\nTileImageOutput: true\\r\\n\\r\\n# if true, an unambiguous date 
time must be provided in the source file's name.\\r\\n# if true, an 
exception will be thrown if no such date is found\\r\\n# if false, and a 
valid date is still found in file name, it will still be parsed\\r\\n# 
supports formats like:\\r\\n# prefix_20140101T235959+1000.mp3\\r\\n# 
prefix_20140101T235959+Z.mp3\\r\\n# 
prefix_20140101-235959+1000.mp3\\r\\n# 
prefix_20140101-235959+Z.mp3\\r\\nRequireDateInFilename: 
true\\r\\n\\r\\nIndexPropertiesConfig: 
'./IndexPropertiesConfig.yml'\\r\\nEventThreshold: 
0.2\\r\\n...\\r\\n\\r\\n\", \"job_id\"=>\"system\", 
\"uuid\"=>\"efb477ae-f3df-4a1b-bbe7-2017439ea36f\", \"id\"=>\"14268\", 
\"datetime_with_offset\"=>\"2008-06-06T17:45:00.000Z\", 
\"original_format\"=>\"wv\"}})", 


````

### PR DESCRIPTION
**Pull request by atruskie**
Fixes #40. Fixes #41. Closes #31.

- Monkey patches resque:status so that TTLs are only set on finished
status
- Ensures resque:status's expire_in option is set for both work and web
startup scenarios
- Forces action implementers to override resque:status' default name
implementation to prevent double encoding of payloads
- Added friendly name methods to all actions
- Introduces the concept of partial payloads (splitting payloads into
variant and invariant parts) to reduce memory usage for large sets of
similar jobs
- It adapts the Analysis action (only) to use partial payloads. Users of
`action_enqueue` need to provide a group key to take advantage of the
functionality.
- We introduce our own Redis communicator for access to Redis outside of
Resque's scope
- It drys up the `config.rb` a bit.
- We add a template action as clean base (mainly done to help @atruskie
learn what is necessary for an Action to implement and what among the
other examples was extraneous to a minimal example).

:grinning:

### CODE REVIEW

File: lib/baw-workers/partial_payload.rb [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+  # Useful for splitting apart large payloads that are stuck in, for example, Redis LISTs.
+  # In the common scenario of using a LIST to store job payloads for a processing system, the large invariant parts
+  # of payloads can be split apart and stored separately. We experience 92-96% less memory usage using this technique
+  # on very large payloads for large job sets (e.g. 1000 or more).
+  # This technique should be used when you have at least 100 payloads which are largely identical.
+  class PartialPayload
+    @communicator = BawWorkers::Config.redis_communicator
+
+    class << self
+      PARTIAL_PAYLOAD_KEY = "payload_base"
```
Comment (cofiem) [inline lib/baw-workers/partial_payload.rb]: These constant names and values don't seem to match.

File: lib/baw-workers/exceptions.rb [hunk 2]
```diff
@@ -10,5 +10,6 @@ class HarvesterAudioToolError < HarvesterIOError; end
     class HarvesterEndpointError < HarvesterError; end
     class HarvesterAnalysisError < HarvesterError; end
     class AnalysisCacheError < StandardError; end
+    class PartialPayloadMissing < StandardError; end
```
Comment (cofiem) [inline lib/baw-workers/exceptions.rb]: This also appears in https://github.com/QutBioacoustics/baw-workers/pull/42/files#diff-afb1ab8a76efa179c9d7f74ea6e0d2bcR3

File: lib/baw-workers/analysis/payload.rb [hunk 3]
```diff
@@ -176,6 +186,34 @@ def self.normalise_opts(opts)
...
+
+        # 1. split out invariant keys
+        invariant = {}
+        BASE_FIELDS.each do |key|
+          raise "analysis_params is missing required key #{key}" unless analysis_params.has_key?(key)
+
+          invariant[key] = analysis_params.delete(key)
+        end
+
+        # 2. check if invariant payload already exists
```
Comment (cofiem) [inline lib/baw-workers/analysis/payload.rb]: Is this implementation complete?

File: lib/baw-workers/partial_payload.rb [hunk 4]
```diff
@@ -0,0 +1,151 @@
...
+  end
+
+  # Stores Redis string payloads in multiple parts.
+  # Useful for splitting apart large payloads that are stuck in, for example, Redis LISTs.
+  # In the common scenario of using a LIST to store job payloads for a processing system, the large invariant parts
+  # of payloads can be split apart and stored separately. We experience 92-96% less memory usage using this technique
+  # on very large payloads for large job sets (e.g. 1000 or more).
+  # This technique should be used when you have at least 100 payloads which are largely identical.
+  class PartialPayload
+    @communicator = BawWorkers::Config.redis_communicator
```
Comment (cofiem) [inline lib/baw-workers/partial_payload.rb]: Does this need to be stored in each class, or could each instance variable reference just refer to `BawWorkers::Config.redis_communicator`?

File: lib/baw-workers/partial_payload.rb [hunk 5]
```diff
@@ -0,0 +1,151 @@
...
+      # @return [Boolean] True if the delete succeeded.
+      def delete_recursive(key)
+        has_namespace = key.include?(':' + REDIS_NAMESPACE + ':')
+        key = add_namespace(key) unless has_namespace
+
+        # first get the partial payload
+        partial = @communicator.get(key, {no_namespace: has_namespace})
+
+        if partial.nil?
+          raise PartialPayloadMissing.new("Could not retrieve partial payload `#{key}`")
```
Comment (cofiem) [inline lib/baw-workers/partial_payload.rb]: Will this leave payloads in an inconsistent state if an error is raised?

File: lib/baw-workers/redis_communicator.rb [hunk 6]
```diff
@@ -0,0 +1,122 @@
+module BawWorkers
+  class DecodeException < StandardError;
```
Comment (cofiem) [inline lib/baw-workers/redis_communicator.rb]: This could be in the error module.

File: lib/baw-workers/redis_communicator.rb [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+
+
+    # @param [String] key
+    # @return [Boolean]
+    def delete(key, opts = {})
+      key = add_namespace(key) unless opts[:no_namespace]
+
+      deleted = @redis.del(key)
+
+      raise 'Too many keys deleted' if deleted > 1
```
Comment (cofiem) [inline lib/baw-workers/redis_communicator.rb]: I'm glad this is checked, but isn't after it deletes too many keys a bit late? Should this do a get first to check the key count?

File: lib/baw-workers/resque_status_custom_expire.rb [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+      ]
+
+      class Hash
+
+        # set a status by UUID. <tt>messages</tt> can be any number of strings or hashes
+        # that are merged in order to create a single status.
+        # WARNING: MONKEY PATCH
+        # https://github.com/quirkey/resque-status/blob/11eb130ad1bc9cbc11aae3bad4d507ee06f5bb0a/lib/resque/plugins/status/hash.rb
+        # Now only sets a TTL IFF status is in the expire list. Thus the status key
+        # has no expire until it has completed/failed/killed.
```
Comment (cofiem) [inline lib/baw-workers/resque_status_custom_expire.rb]: Clever! Cool if this works!

File: spec/lib/baw-workers/analysis/payload_spec.rb [hunk 9]
```diff
@@ -1,12 +1,159 @@
...
+        "sub_folders" => ['hello', 'here_i_am'],
+        "config" => 'blah a very long and repeated blob of text' * 300,
+        "file_executable" => "echo",
+        "copy_paths" => []
+
+    }
+  }
+
+
+  it 'stores and retrieves partial payloads' do
```
Comment (cofiem) [inline spec/lib/baw-workers/analysis/payload_spec.rb]: This test failed for me:

````
Failures:

  1) BawWorkers::Analysis::Payload stores and retrieves partial payloads
     Failure/Error: expect(found1.size).to eq(1)
     
       expected: 1
            got: 0
     
       (compared using ==)
     # ./spec/lib/baw-workers/analysis/payload_spec.rb:123:in `block (2 levels) in <top (required)>'

Finished in 1 minute 6.13 seconds (files took 1.9 seconds to load)
221 examples, 1 failure

````

File: lib/baw-workers/analysis/payload.rb (hunk 3 above)
Comment (atruskie) [inline lib/baw-workers/analysis/payload.rb]: ah yes, those notes got refactored into `BawWorkers::PartialPayload.create_or_validate`

File: lib/baw-workers/exceptions.rb (hunk 2 above)
Comment (atruskie) [inline lib/baw-workers/exceptions.rb]: good catch

File: lib/baw-workers/partial_payload.rb (hunk 4 above)
Comment (atruskie) [inline lib/baw-workers/partial_payload.rb]: TBH I don't understand the different. I was using `@communicator` just to alias the `BawWorkers::Config.redis_communicator`. 

Actually, I remember now... it needed to be there or it caused an error. I originally had it in inside the `class << self` defintion but I had to move it there.

File: lib/baw-workers/partial_payload.rb (hunk 1 above)
Comment (atruskie) [inline lib/baw-workers/partial_payload.rb]: Yeah, they don't.  The constant name describes what the value is used for, the value makes more sense when you're looking at a payload ('why is this payload so small? oh I see it has a base payload over there...'). I thought this was self explanatory?

File: lib/baw-workers/partial_payload.rb (hunk 5 above)
Comment (atruskie) [inline lib/baw-workers/partial_payload.rb]: Yes... but if it can't be found it is already in an inconsistent state. Any other choices?

File: lib/baw-workers/redis_communicator.rb (hunk 6 above)
Comment (atruskie) [inline lib/baw-workers/redis_communicator.rb]: What's the reasoning for moving to the error module?

I left it here because it came with the code I blatantly lifted from Resque.

File: lib/baw-workers/redis_communicator.rb (hunk 7 above)
Comment (atruskie) [inline lib/baw-workers/redis_communicator.rb]: This is just a safety clause. I designed intended the method to delete one value at a time. But this is really just a very thin wrapper around the Redis API and it returns an int - so this was me dealing with possibly unintentional behaviour. This is not even unit tested...

File: lib/baw-workers/resque_status_custom_expire.rb (hunk 8 above)
Comment (atruskie) [inline lib/baw-workers/resque_status_custom_expire.rb]: should do, there're even tests! :worried:

File: lib/baw-workers/partial_payload.rb (hunk 4 above)
Comment (cofiem) [inline lib/baw-workers/partial_payload.rb]: yeah, having to move it makes sense. Can stay as-is, should be ok.

File: spec/lib/baw-workers/analysis/payload_spec.rb (hunk 9 above)
Comment (atruskie) [inline spec/lib/baw-workers/analysis/payload_spec.rb]: I had so much trouble getting these tests correct. The `ResqueJobId` code does not order the options hashes... which means hashes that are equivalent can still produce different MD5s as their "uuid".

Anyway this was working for me this afternoon - I'll double check again tomorrow. 

Are you using ruby 2.3.1?

File: lib/baw-workers/partial_payload.rb (hunk 5 above)
Comment (cofiem) [inline lib/baw-workers/partial_payload.rb]: I guess not really. Want to know, so this is ok.

File: spec/lib/baw-workers/analysis/payload_spec.rb (hunk 9 above)
Comment (cofiem) [inline spec/lib/baw-workers/analysis/payload_spec.rb]: Yes, 2.3.1.

Error is on the check comparing the size of the found1 array. https://github.com/QutBioacoustics/baw-workers/pull/42/files#diff-fd2c3b29f76f9da90fd4e4832383c710R123

Not sure what's up, could be an issue with the order of args...

Comment (atruskie) [inline spec/lib/baw-workers/analysis/payload_spec.rb]: yeah and it returns 0 results if the payload is not correct and does not forms the correct uuid hash... etc...
